### ISSUE TITLE
Can projects made with Python or Lua be built to exe/binary?

### ISSUE THREAD

**Issue by rootVIII** [harfang3d/harfang3d#31]
Is it possible to build a Harfang3d project to exe or binary when using high level scripting languages (Python/Lua)?

I am picturing something similar to https://docs.panda3d.org/1.10/python/distribution/building-binaries. 

If it is possible, can it be added to your documentation? Otherwise it's definitely a Feature Request that I would ask for.
Thank you! And the project looks great btw...

**Comment by astrofra** [comment]
Hi, on the Python side, we either use **PyInstaller** or the **Embeddable version** of Python (that actually doesn't really make a standalone executable). We will indeed prepare a documentation page on this topic.
Regarding Lua, we simply need to prepare a binary bootstrap that will automatic load a "data" package, in ZIP format. That should cover most of the use cases.

What if you language of choice ? Python or Lua ?

**Comment by rootVIII** [comment]
Oh thank you.

Yes, I read a little more and realized that you are offering the SDK... so it's understandable that there wouldn't be a way to build Python binaries except for the existing methods (such as Pyinstaller).

I prefer Python or Go... But I may just try your harfang-go project as that looks promising and most likely solves my building to exe issue with ``` go build ```.

I am guessing that either way, the Harfang SDK needs to be bundled with the final/distributable project?

I think once the documentation gets improved etc. I will be very interested in a paid subscription (assuming I figure out the API offered in the SDK etc). Thanks again...
